apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432        # port clients use
      targetPort: 5432  # port exposed by the PostgreSQL container
  type: ClusterIP       # default, internal access only
